/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aeontanvir;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aeon
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();

        //setLocation
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        updateUser();
        updateCmbId();
        updateInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        companyName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        companyAddress = new javax.swing.JTextArea();
        companyEmail = new javax.swing.JTextField();
        companyMobile = new javax.swing.JTextField();
        btnCominfoUpdate = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        bankName = new javax.swing.JTextField();
        bankAccountNo = new javax.swing.JTextField();
        bankAccountType = new javax.swing.JTextField();
        bankLedgerNo = new javax.swing.JTextField();
        btnBankInfoUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserFullName = new javax.swing.JTextField();
        txtUserUsername = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JTextField();
        cmbUserPriority = new javax.swing.JComboBox<String>();
        btnUserAdd = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnUserUpdateAdd = new javax.swing.JButton();
        cmbUserUpdatePriority = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUserUpdatePassword = new javax.swing.JTextField();
        txtUserUpdateUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUserUpdateFullName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbUserUpdateId = new javax.swing.JComboBox<String>();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cmbUserDeleteId = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        txtUserDeleteFullName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtUserDeleteUsername = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtUserDeletePassword = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbUserDeletePriority = new javax.swing.JComboBox<String>();
        btnUserDeleteUpdateAdd = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jUserTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Panel");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Company"));

        jLabel15.setText("Company Name");

        jLabel16.setText("Company Address");

        jLabel17.setText("Company Email");

        jLabel18.setText("Company Mobile");

        companyAddress.setColumns(15);
        companyAddress.setRows(3);
        jScrollPane2.setViewportView(companyAddress);

        btnCominfoUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCominfoUpdate.setText("Update Company Information");
        btnCominfoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCominfoUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(companyName)
                    .addComponent(jScrollPane2)
                    .addComponent(companyEmail)
                    .addComponent(companyMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCominfoUpdate)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel16)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel17)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(companyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(companyEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(companyMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnCominfoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Bank"));

        jLabel19.setText("Bank Name");

        jLabel20.setText("Account No");

        jLabel21.setText("Account Type");

        jLabel22.setText("Account Ledger No");

        btnBankInfoUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBankInfoUpdate.setText("Update Bank Information");
        btnBankInfoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBankInfoUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBankInfoUpdate)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bankName)
                            .addComponent(bankAccountNo)
                            .addComponent(bankAccountType)
                            .addComponent(bankLedgerNo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(bankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(bankAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(bankAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(bankLedgerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBankInfoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Company Info", jPanel1);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Full Name");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Act As");

        cmbUserPriority.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal User", "Admin" }));

        btnUserAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUserAdd.setText("Add User");
        btnUserAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtUserUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(txtUserFullName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUserPassword)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbUserPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))))
                .addGap(30, 30, 30))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUserUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbUserPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Add User", jPanel6);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        btnUserUpdateAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUserUpdateAdd.setText("User Update");
        btnUserUpdateAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserUpdateAddActionPerformed(evt);
            }
        });

        cmbUserUpdatePriority.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal User", "Admin" }));

        jLabel5.setText("Act As");

        jLabel6.setText("Password");

        jLabel7.setText("Username");

        jLabel8.setText("Full Name");

        jLabel9.setText("ID");

        cmbUserUpdateId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUserUpdateIdItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUserUpdateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbUserUpdatePriority, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUserUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUserUpdateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUserUpdateFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbUserUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbUserUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUserUpdateFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUserUpdateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUserUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUserUpdatePriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnUserUpdateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Update User", jPanel7);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("ID");

        cmbUserDeleteId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUserDeleteIdItemStateChanged(evt);
            }
        });

        jLabel11.setText("Full Name");

        txtUserDeleteFullName.setEditable(false);

        jLabel12.setText("Username");

        txtUserDeleteUsername.setEditable(false);

        jLabel13.setText("Password");

        txtUserDeletePassword.setEditable(false);

        jLabel14.setText("Act As");

        cmbUserDeletePriority.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal User", "Admin" }));

        btnUserDeleteUpdateAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUserDeleteUpdateAdd.setText("User Delete");
        btnUserDeleteUpdateAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDeleteUpdateAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUserDeleteUpdateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbUserDeletePriority, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUserDeletePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUserDeleteUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUserDeleteFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbUserDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbUserDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtUserDeleteFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtUserDeleteUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtUserDeletePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUserDeletePriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(btnUserDeleteUpdateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Delete User", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("User List"));
        jPanel9.setForeground(new java.awt.Color(153, 153, 153));

        jUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "User", "Password", "Priority"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jUserTable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("User Info", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAddActionPerformed
        if ("".equals(txtUserFullName.getText()) || "".equals(txtUserUsername.getText()) || "".equals(txtUserPassword.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Enter value on field");
        } else {
            Connection conn = null;
            PreparedStatement psm = null;
            try {
                int type = 0;
                if (cmbUserPriority.getSelectedIndex() == 1) {
                    type = 1;
                }
                conn = DatabaseConnection.getConnection();
                String sql = "INSERT INTO user(username, password, fullname, type) VALUES(?,?,?,?)";
                psm = conn.prepareStatement(sql);
                psm.setString(1, txtUserUsername.getText());
                psm.setString(2, txtUserPassword.getText());
                psm.setString(3, txtUserFullName.getText());
                psm.setString(4, "" + type);

                int t = psm.executeUpdate();
                if (t > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Add user successfully");
                    txtUserUsername.setText("");
                    txtUserFullName.setText("");
                    txtUserPassword.setText("");
                    cmbUserPriority.setSelectedIndex(0);
                    updateUser();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "No entry execute successfully");
                    try {
                        ErrorHelper.exceptionError("btnUserAddActionPerformed");
                    } catch (Exception ex) {
                    }
                }
            } catch (Exception ex) {
                System.err.println("btnUserAddActionPerformed" + ex);
            } finally {
                if (conn != null || psm != null) {
                    try {
                        conn.close();
                        psm.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        }
    }//GEN-LAST:event_btnUserAddActionPerformed

    private void btnUserUpdateAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserUpdateAddActionPerformed
        if (cmbUserUpdateId.getSelectedIndex() > 0) {
            Connection conn = null;
            PreparedStatement psm = null;
            ResultSet rs = null;
            try {
                conn = DatabaseConnection.getConnection();
                String sql = "UPDATE user "
                        + "SET "
                        + "username = ?, "
                        + "password = ?, "
                        + "fullname = ?, "
                        + "type = ? "
                        + "WHERE id = ?";

                psm = conn.prepareStatement(sql);

                psm.setString(1, txtUserUpdateUsername.getText());
                psm.setString(2, txtUserUpdateUsername.getText());
                psm.setString(3, txtUserUpdatePassword.getText());
                psm.setString(4, "" + cmbUserUpdatePriority.getSelectedIndex());
                psm.setString(5, cmbUserUpdateId.getSelectedItem().toString());

                int n = psm.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Update user successfully");
                    updateCmbId();
                    updateUser();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No Entry Update");
                }

            } catch (Exception ex) {
                System.err.println("btnUserUpdateAddActionPerformed" + ex);
            } finally {
                if (conn != null || psm != null) {
                    try {
                        conn.close();
                        psm.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnUserUpdateAddActionPerformed

    private void cmbUserUpdateIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUserUpdateIdItemStateChanged
        Connection conn = null;
        PreparedStatement psm = null;
        ResultSet rs = null;
        if (cmbUserUpdateId.getSelectedIndex() > 0) {
            try {
                conn = DatabaseConnection.getConnection();
                String sql = "SELECT * FROM user WHERE id = ?";
                psm = conn.prepareStatement(sql);
                String id = cmbUserUpdateId.getSelectedItem().toString();
                psm.setString(1, id);
                rs = psm.executeQuery();
                if (rs.next()) {
                    txtUserUpdateFullName.setText(rs.getString(4));
                    txtUserUpdateUsername.setText(rs.getString(2));
                    txtUserUpdatePassword.setText(rs.getString(3));
                    cmbUserUpdatePriority.setSelectedIndex(rs.getInt(5));
                }
            } catch (Exception ex) {
                System.err.println("cmbUserUpdateIdItemStateChanged Error" + ex);
            } finally {
                if (conn != null || psm != null) {
                    try {
                        conn.close();
                        psm.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            txtUserUpdateFullName.setText("");
            txtUserUpdateUsername.setText("");
            txtUserUpdatePassword.setText("");
            cmbUserUpdatePriority.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmbUserUpdateIdItemStateChanged

    private void cmbUserDeleteIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUserDeleteIdItemStateChanged
        Connection conn = null;
        PreparedStatement psm = null;
        ResultSet rs = null;
        if (cmbUserDeleteId.getSelectedIndex() > 0) {
            try {
                conn = DatabaseConnection.getConnection();
                String sql = "SELECT * FROM user WHERE id = ?";
                psm = conn.prepareStatement(sql);
                String id = cmbUserDeleteId.getSelectedItem().toString();
                psm.setString(1, id);
                rs = psm.executeQuery();
                if (rs.next()) {
                    txtUserDeleteFullName.setText(rs.getString(4));
                    txtUserDeleteUsername.setText(rs.getString(2));
                    txtUserDeletePassword.setText(rs.getString(3));
                    cmbUserDeletePriority.setSelectedIndex(rs.getInt(5));
                }
            } catch (Exception ex) {
                System.err.println("cmbUserDeleteIdItemStateChanged Error" + ex);
            } finally {
                if (conn != null || psm != null) {
                    try {
                        conn.close();
                        psm.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            txtUserDeleteFullName.setText("");
            txtUserDeleteUsername.setText("");
            txtUserDeletePassword.setText("");
            cmbUserDeletePriority.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmbUserDeleteIdItemStateChanged

    private void btnUserDeleteUpdateAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDeleteUpdateAddActionPerformed
        if (cmbUserDeleteId.getSelectedIndex() > 0) {
            Connection conn = null;
            PreparedStatement psm = null;
            ResultSet rs = null;
            try {
                conn = DatabaseConnection.getConnection();
                String sql = "DELETE FROM user WHERE id= ? ";

                psm = conn.prepareStatement(sql);
                psm.setString(1, cmbUserDeleteId.getSelectedItem().toString());

                int n = psm.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Delete user successfully");
                    updateCmbId();
                    updateUser();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No Entry Update");
                }

            } catch (Exception ex) {
                System.err.println("btnUserDeleteUpdateAddActionPerformed" + ex);
            } finally {
                if (conn != null || psm != null) {
                    try {
                        conn.close();
                        psm.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnUserDeleteUpdateAddActionPerformed

    private void btnBankInfoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBankInfoUpdateActionPerformed
        String bName = bankName.getText().toString();
        String bAccountNo = bankAccountNo.getText().toString();
        String bType = bankAccountType.getText().toString();
        String bLedgerNo = bankLedgerNo.getText().toString();
        if ("".equals(bName) || "".equals(bAccountNo) || "".equals(bType) || "".equals(bLedgerNo)) {
            JOptionPane.showMessageDialog(rootPane, "Enter value on field");
        } else {
            Connection conn = null;
            PreparedStatement psm = null;
            try {
                conn = DatabaseConnection.getConnection();
                String sql ="UPDATE bank_info SET bank_name = ? , account_no = ?, account_type = ? , ledger_no = ? WHERE id = 1";

                psm = conn.prepareStatement(sql);

                psm.setString(1, bName);
                psm.setString(2, bAccountNo);
                psm.setString(3, bType);
                psm.setString(4, bLedgerNo);

                int n = psm.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Update bank info successfully");
                    updateBankInfo();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No Entry Update");
                }

            } catch (Exception ex) {
                System.err.println("btnBankInfoUpdateActionPerformed" + ex);
            } finally {
                if (conn != null || psm != null) {
                    try {
                        conn.close();
                        psm.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnBankInfoUpdateActionPerformed

    private void btnCominfoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCominfoUpdateActionPerformed
        String cName = companyName.getText().toString();
        String cAddress = companyAddress.getText().toString();
        String cEmail = companyEmail.getText().toString();
        String cMobile = companyMobile.getText().toString();
        if ("".equals(cName) || "".equals(cAddress) || "".equals(cEmail) || "".equals(cMobile)) {
            JOptionPane.showMessageDialog(rootPane, "Enter value on field");
        } else {
            Connection conn = null;
            PreparedStatement psm = null;
            try {
                conn = DatabaseConnection.getConnection();
                String sql ="UPDATE company_info SET company_name = ? , company_address = ?, company_email = ?, company_mobile = ? WHERE id = 1";

                psm = conn.prepareStatement(sql);

                psm.setString(1, cName);
                psm.setString(2, cAddress);
                psm.setString(3, cEmail);
                psm.setString(4, cMobile);

                int n = psm.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Update company info successfully");
                    updateCompanyInfo();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No Entry Update");
                }

            } catch (Exception ex) {
                System.err.println("btnCominfoUpdateActionPerformed" + ex);
            } finally {
                if (conn != null || psm != null) {
                    try {
                        conn.close();
                        psm.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnCominfoUpdateActionPerformed

    private void updateCmbId() {
        Connection conn = null;
        PreparedStatement psm = null;
        ResultSet rs = null;
        try {
            conn = DatabaseConnection.getConnection();
            String sql = "SELECT * FROM user";
            psm = conn.prepareStatement(sql);

            rs = psm.executeQuery();

            List pList = new ArrayList();
            while (rs.next()) {
                pList.add(rs.getInt(1));
            }
            cmbUserUpdateId.setModel(new DefaultComboBoxModel(pList.toArray()));
            cmbUserUpdateId.insertItemAt("--Select One--", 0);
            cmbUserUpdateId.setSelectedIndex(0);
            cmbUserDeleteId.setModel(new DefaultComboBoxModel(pList.toArray()));
            cmbUserDeleteId.insertItemAt("--Select One--", 0);
            cmbUserDeleteId.setSelectedIndex(0);
        } catch (Exception ex) {
            System.err.println("updateCmbId" + ex);
        } finally {
            if (conn != null || psm != null) {
                try {
                    conn.close();
                    psm.close();
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    public void updateUser() {
        ResultSet rs = null;
        Connection conn = null;
        PreparedStatement psm = null;
        try {
            conn = DatabaseConnection.getConnection();
            String sql = "SELECT * FROM user";

            psm = conn.prepareStatement(sql);

            rs = psm.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) jUserTable.getModel();
            dtm.setRowCount(0);
            Object[] tempObject = new Object[5];

            while (rs.next()) {
                tempObject[0] = rs.getInt(1);
                tempObject[1] = rs.getString(4);
                tempObject[2] = rs.getString(2);
                tempObject[3] = rs.getString(3);
                tempObject[4] = rs.getInt(5);
                dtm.addRow(tempObject);
            }
        } catch (Exception e) {
            System.out.println("updateUser" + e);
        } finally {
            if (conn != null || psm != null) {
                try {
                    conn.close();
                    psm.close();
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private void updateCompanyInfo() {
        Connection conn = null;
        PreparedStatement psm = null;
        ResultSet rs = null;
        try {
            conn = DatabaseConnection.getConnection();
            String sql = "SELECT * FROM company_info";
            psm = conn.prepareStatement(sql);
            rs = psm.executeQuery();
            if (rs.next()) {
                companyName.setText(rs.getString(2));
                companyAddress.setText(rs.getString(3));
                companyEmail.setText(rs.getString(4));
                companyMobile.setText(rs.getString(5));
            }

        } catch (Exception e) {
        } finally {
            if (conn != null || psm != null) {
                try {
                    conn.close();
                    psm.close();
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private void updateBankInfo() {
        Connection conn = null;
        PreparedStatement psm = null;
        ResultSet rs = null;
        try {
            conn = DatabaseConnection.getConnection();
            String sql = "SELECT * FROM bank_info";
            psm = conn.prepareStatement(sql);
            rs = psm.executeQuery();
            if (rs.next()) {
                bankName.setText(rs.getString(2));
                bankAccountNo.setText(rs.getString(3));
                bankAccountType.setText(rs.getString(4));
                bankLedgerNo.setText(rs.getString(5));
            }

        } catch (Exception e) {
        } finally {
            if (conn != null || psm != null) {
                try {
                    conn.close();
                    psm.close();
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private void updateInfo() {
        updateCompanyInfo();
        updateBankInfo();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bankAccountNo;
    private javax.swing.JTextField bankAccountType;
    private javax.swing.JTextField bankLedgerNo;
    private javax.swing.JTextField bankName;
    private javax.swing.JButton btnBankInfoUpdate;
    private javax.swing.JButton btnCominfoUpdate;
    private javax.swing.JButton btnUserAdd;
    private javax.swing.JButton btnUserDeleteUpdateAdd;
    private javax.swing.JButton btnUserUpdateAdd;
    private javax.swing.JComboBox<String> cmbUserDeleteId;
    private javax.swing.JComboBox<String> cmbUserDeletePriority;
    private javax.swing.JComboBox<String> cmbUserPriority;
    private javax.swing.JComboBox<String> cmbUserUpdateId;
    private javax.swing.JComboBox<String> cmbUserUpdatePriority;
    private javax.swing.JTextArea companyAddress;
    private javax.swing.JTextField companyEmail;
    private javax.swing.JTextField companyMobile;
    private javax.swing.JTextField companyName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jUserTable;
    private javax.swing.JTextField txtUserDeleteFullName;
    private javax.swing.JTextField txtUserDeletePassword;
    private javax.swing.JTextField txtUserDeleteUsername;
    private javax.swing.JTextField txtUserFullName;
    private javax.swing.JTextField txtUserPassword;
    private javax.swing.JTextField txtUserUpdateFullName;
    private javax.swing.JTextField txtUserUpdatePassword;
    private javax.swing.JTextField txtUserUpdateUsername;
    private javax.swing.JTextField txtUserUsername;
    // End of variables declaration//GEN-END:variables
}
