/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aeontanvir;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author aeon
 */
public class LoginFrame extends javax.swing.JFrame {
    int loginTry = 1;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();

        //setLocation
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panForBg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLogPassword = new javax.swing.JPasswordField();
        txtLogUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setName("loginFrame"); // NOI18N
        setResizable(false);

        panForBg.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        panForBg.add(jLabel2);
        jLabel2.setBounds(60, 140, 80, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        panForBg.add(jLabel3);
        jLabel3.setBounds(60, 190, 80, 17);

        txtLogPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panForBg.add(txtLogPassword);
        txtLogPassword.setBounds(170, 180, 240, 30);

        txtLogUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panForBg.add(txtLogUsername);
        txtLogUsername.setBounds(170, 130, 240, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        panForBg.add(jLabel1);
        jLabel1.setBounds(210, 70, 90, 30);

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 0, 0));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panForBg.add(btnLogin);
        btnLogin.setBounds(320, 230, 90, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aeontanvir/img/logkey.png"))); // NOI18N
        panForBg.add(jLabel4);
        jLabel4.setBounds(160, 60, 50, 50);

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Powered by : www.aeontanvir.com");
        panForBg.add(jLabel5);
        jLabel5.setBounds(280, 290, 200, 20);

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aeontanvir/img/login.jpg"))); // NOI18N
        panForBg.add(lblBg);
        lblBg.setBounds(0, 0, 490, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panForBg, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panForBg, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        if ("".equals(txtLogUsername.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Enter username!");
            txtLogUsername.requestFocus();
        } else if ("".equals(txtLogPassword.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Enter password!");
            txtLogPassword.requestFocus();
        } else {
            Connection conn = null;
            PreparedStatement pstm = null;
            ResultSet rs = null;
            try {
                conn = DatabaseConnection.getConnection();
                String sql = "SELECT * FROM user WHERE username = ? and password = ?";
                pstm = conn.prepareStatement(sql);
                pstm.setString(1, txtLogUsername.getText());
                pstm.setString(2, txtLogPassword.getText());

                rs = pstm.executeQuery();
                if (rs.next()) {
                    ErrorHelper.login("Login - MainWindow : " + "UserName : "+txtLogUsername.getText());
                    txtLogUsername.setText("");
                    txtLogPassword.setText("");
                    //setLocation
                    MainFrame mainFrame = new MainFrame();
                    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                    mainFrame.setLocation(dim.width / 2 - mainFrame.getSize().width / 2, dim.height / 2 - mainFrame.getSize().height / 2);
                    mainFrame.setVisible(true);
                } else {
                    loginTry = loginTry + 1;
                    if(loginTry == 6){
                        ErrorHelper.loginError("System Exit - "+"Wrong username and password : " + txtLogUsername.getText() + "|" + txtLogPassword.getText());
                        System.exit(1);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Check username and password correctly!");
                    ErrorHelper.loginError("Wrong username and password : " + txtLogUsername.getText() + "|" + txtLogPassword.getText());
                    txtLogPassword.setText("");
                    txtLogPassword.requestFocus();
                }

            } catch (Exception e) {
                try {
                    ErrorHelper.exceptionError("LoginFrame btnLoginActionPerformed Error \t" + e);
                } catch (Exception ex) {
                    System.err.println("123654753");
                }
                System.err.println("LoginFrame btnLoginActionPerformed Error \t" + e);
            }finally{
                try {
                    conn.close();
                    pstm.close();
                    rs.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBg;
    private javax.swing.JPanel panForBg;
    private javax.swing.JPasswordField txtLogPassword;
    private javax.swing.JTextField txtLogUsername;
    // End of variables declaration//GEN-END:variables
}
